In [2]:
import pandas as pd
import numpy as np

In [3]:
data = {
    "Hours_Studied": [4.0, 6.0, 5.0, 7.0, 3.0],
    "Attendance": [80, 90, 85, 95, 70],
    "Assignment_Score": [75, 85, 78, 92, 65],
    "Sleep_Hours": [6.0, 7.0, 5.0, np.nan, 4.0],
    "Final_Grade": ['B', 'A', 'B', 'A', 'C']
}

In [4]:
df = pd.DataFrame(data)

In [5]:
df

   Hours_Studied  Attendance  Assignment_Score  Sleep_Hours Final_Grade
0            4.0          80                75          6.0           B
1            6.0          90                85          7.0           A
2            5.0          85                78          5.0           B
3            7.0          95                92          NaN           A
4            3.0          70                65          4.0           C

In [8]:
df.columns

Index(['Hours_Studied', 'Attendance', 'Assignment_Score', 'Sleep_Hours',
       'Final_Grade'],
      dtype='object')

In [9]:
df.dtypes

Hours_Studied       float64
Attendance            int64
Assignment_Score      int64
Sleep_Hours         float64
Final_Grade          object
dtype: object

In [10]:
df.isnull()

   Hours_Studied  Attendance  Assignment_Score  Sleep_Hours  Final_Grade
0          False       False             False        False        False
1          False       False             False        False        False
2          False       False             False        False        False
3          False       False             False         True        False
4          False       False             False        False        False

In [11]:
df["Hours_Studied"]

0    4.0
1    6.0
2    5.0
3    7.0
4    3.0
Name: Hours_Studied, dtype: float64